version: "3"
services:
# My grafana service 
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 52.49.174.5:9000:3000
    volumes:
      - grafana-data:/var/lib/grafana
# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
    external: true
